java:
  - openjdk8
os:
  - ubuntu/bionic64/java-driver
cassandra:
  - '3.11'
env:
  GUAVA_VERSION:
    - '16.0.1'
    - '17.0'
    - '18.0'
    - '19.0'
    - '20.0'
    - '21.0'
    - '22.0'
    - '23.6.1-jre'
    - '24.1.1-jre'
    - '25.1-jre'
    - '26.0-jre'
build:
  - script: |
      . /usr/local/bin/jdk_switcher.sh
      jdk_switcher use openjdk8
      export MAVEN_HOME=/home/jenkins/.mvn/apache-maven-3.2.5
      export PATH=$MAVEN_HOME/bin:$PATH
      mvn -B -V install -DskipTests
  - script: |
      . /usr/local/bin/jdk_switcher.sh
      jdk_switcher use $JAVA_VERSION
  - type: maven
    version: 3.2.5
    goals: verify --fail-never -Plong
    properties: |
      com.datastax.driver.TEST_BASE_NODE_WAIT=120
      com.datastax.driver.NEW_NODE_DELAY_SECONDS=100
      cassandra.version=$CCM_CASSANDRA_VERSION
      ccm.java.home=$CCM_JAVA_HOME
      ccm.path=$CCM_JAVA_HOME/bin
      ccm.maxNumberOfNodes=3
      failIfNoTests=false
      maven.test.failure.ignore=true
      maven.javadoc.skip=true
      guava.version=$GUAVA_VERSION
  - type: maven
    version: 3.2.5
    goals: verify --fail-never -Pisolated
    properties: |
      com.datastax.driver.TEST_BASE_NODE_WAIT=120
      com.datastax.driver.NEW_NODE_DELAY_SECONDS=100
      cassandra.version=$CCM_CASSANDRA_VERSION
      ccm.java.home=$CCM_JAVA_HOME
      ccm.path=$CCM_JAVA_HOME/bin
      ccm.maxNumberOfNodes=3
      failIfNoTests=false
      maven.test.failure.ignore=true
      maven.javadoc.skip=true
      guava.version=$GUAVA_VERSION
  - xunit:
    - "**/target/surefire-reports/TEST-*.xml"
    - "**/target/failsafe-reports/TEST-*.xml" 
